site_name: IntelChair
nav:
    - Home: index.md
    - Client: client.md
    - Vision: vision.md
    - Manual: manual.md
    - Architecture: arch.md
    - Requirements: requirements.md
    - Deliverables: deliv.md
    - Team: team.md
theme: readthedocs

markdown_extensions:
    - attr_list