site_name: UberChair
nav:
    - Home: index.md
    - Client: client.md
    - Manual: manual.md
    - Specification: spec.md
    - Developer: dev.md
    - Personas: personas.md
    - About: about.md
theme: readthedocs